SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS OUTS
LEFT OUTER JOIN ANIMAL_INS INS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.ANIMAL_ID is null
ORDER BY ANIMAL_ID;

 # -- A 테이블에만 존재하는 항목
# select A.EMPNO
# from tableA A left outer join tableB B on A.EMPNO=B.EMPNO