SELECT outs.ANIMAL_ID, outs.NAME
FROM ANIMAL_OUTS AS outs
LEFT JOIN ANIMAL_INS AS ins
ON outs.ANIMAL_ID = ins.ANIMAL_ID
WHERE outs.SEX_UPON_OUTCOME IS NOT NULL
ORDER BY (outs.DATETIME - ins.DATETIME) DESC
LIMIT 2;