SELECT u.USER_ID, u.NICKNAME, CONCAT_WS(' ', CITY, STREET_ADDRESS1, STREET_ADDRESS2) as 전체주소, CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8, 4)) as 전화번호
FROM USED_GOODS_BOARD as b
JOIN USED_GOODS_USER as u
ON b.WRITER_ID = u.USER_ID
GROUP BY u.USER_ID
HAVING COUNT(u.USER_ID) >= 3
ORDER BY u.USER_ID DESC;