SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE, '%Y-%m-%d') as START_DATE, DATE_FORMAT(END_DATE, '%Y-%m-%d') as END_DATE, if(DATEDIFF(END_DATE, START_DATE)+1 < 30, '단기 대여', '장기 대여') as RENT_TYPE FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE >= '2022-09-01' AND START_DATE < '2022-10-01'
        ORDER BY HISTORY_ID
        DESC;





# SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE, '%Y-%m-%d') as START_DATE, DATE_FORMAT(END_DATE, '%Y-%m-%d') as END_DATE, IF(DATEDIFF(END_DATE, START_DATE) >= 30, '장기대여', '단기대여') as RENT_TYPE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE LIKE '2022-09%'
# ORDER BY HISTORY_ID DESC;























