SELECT p.PRODUCT_ID, p.PRODUCT_NAME, p.PRICE * SUM(o.AMOUNT)  as TOTAL_SALES
FROM FOOD_PRODUCT as p
JOIN FOOD_ORDER as o
ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE o.PRODUCE_DATE LIKE '2022-05%'
GROUP BY p.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID;















# SELECT pro.PRODUCT_ID, pro.PRODUCT_NAME, SUM(pro.PRICE * ord.AMOUNT) as TOTAL_SALES
# FROM FOOD_PRODUCT pro
# JOIN FOOD_ORDER ord ON pro.PRODUCT_ID = ord.PRODUCT_ID
# WHERE month(ord.PRODUCE_DATE) = 5
# GROUP BY pro.PRODUCT_NAME
# ORDER BY TOTAL_SALES DESC, pro.PRODUCT_ID;