SELECT pro.PRODUCT_ID, pro.PRODUCT_NAME, SUM(pro.PRICE * ord.AMOUNT) as TOTAL_SALES
FROM FOOD_PRODUCT pro
JOIN FOOD_ORDER ord ON pro.PRODUCT_ID = ord.PRODUCT_ID
WHERE month(ord.PRODUCE_DATE) = 5
GROUP BY pro.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, pro.PRODUCT_ID;