SELECT car.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR as car
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as his
ON car.CAR_ID = his.CAR_ID
WHERE his.START_DATE LIKE '2022-10%' AND car.CAR_TYPE = '세단'
GROUP BY car.CAR_ID
ORDER BY car.CAR_ID DESC;





















# SELECT DISTINCT(CAR.CAR_ID)
# FROM CAR_RENTAL_COMPANY_CAR as CAR
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as HISTORY
# ON CAR.CAR_ID = HISTORY.CAR_ID
# WHERE CAR_TYPE = '세단' AND MONTH(START_DATE) = '10'
# ORDER BY CAR.CAR_ID DESC;